-- Drop all tables
DROP TABLE IF EXISTS TrafficDensity;
DROP TABLE IF EXISTS TrafficSignalData;
DROP TABLE IF EXISTS TrafficSignal;
DROP TABLE IF EXISTS Notification;
DROP TABLE IF EXISTS ChipiButtonSensorData;
DROP TABLE IF EXISTS ChipiButtonSensor;
DROP TABLE IF EXISTS GasSensorData;
DROP TABLE IF EXISTS GasSensor;
DROP TABLE IF EXISTS SoundSensorData;
DROP TABLE IF EXISTS SoundSensor;
DROP TABLE IF EXISTS TemperatureSensorData;
DROP TABLE IF EXISTS TemperatureSensor;
DROP TABLE IF EXISTS DeviceLocation;
DROP TABLE IF EXISTS RoadCrossRoad;
DROP TABLE IF EXISTS Road;
DROP TABLE IF EXISTS CrossRoad;
DROP TABLE IF EXISTS User;

DROP TABLE IF EXISTS User;
CREATE TABLE User (
    Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(20) UNIQUE,
    Password VARCHAR(2000),
    UrlAvatar VARCHAR(1000),
    Name VARCHAR(200),
    Ranks VARCHAR(200),
    BirthDate DATE,
    Sex BOOLEAN,
    WorkPlace VARCHAR(200),
    IdNo VARCHAR(15),
    Religion VARCHAR(200),
    CreateAt DATETIME,
    UpdateAt DATETIME
);

DROP TABLE IF EXISTS CrossRoad;
CREATE TABLE CrossRoad (
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200),
    Latitude DOUBLE,
    Longtitude DOUBLE,
	CreateAt DATETIME,
    UpdateAt DATETIME
);

DROP TABLE IF EXISTS Road;
CREATE TABLE Road (
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200),
    CreateAt DATETIME,
    UpdateAt DATETIME
);

DROP TABLE IF EXISTS RoadCrossRoad;
CREATE TABLE RoadCrossRoad (
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    RoadId INTEGER,
    CrossRoadId INTEGER,
	CreateAt DATETIME,
    UpdateAt DATETIME,
	FOREIGN KEY (RoadId) REFERENCES Road(Id) 
		ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CrossRoadId) REFERENCES CrossRoad(Id) 
		ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS DeviceLocation;
CREATE TABLE DeviceLocation (
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    RoadCrossRoadId INTEGER,
    IsNorth BOOLEAN,
	CreateAt DATETIME,
    UpdateAt DATETIME,
	FOREIGN KEY (RoadCrossRoadId) REFERENCES RoadCrossRoad(Id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS TemperatureSensor;
CREATE TABLE TemperatureSensor (
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    LocationId INTEGER,
	CreateAt DATETIME,
    UpdateAt DATETIME,
    FOREIGN KEY (LocationId) REFERENCES DeviceLocation(Id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS TemperatureSensorData;
CREATE TABLE TemperatureSensorData (
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    DeviceId INTEGER,
    Value DOUBLE,
    Time TIMESTAMP,
	CreateAt DATETIME,
    UpdateAt DATETIME,
    FOREIGN KEY (DeviceId) REFERENCES TemperatureSensor(Id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS SoundSensor;
CREATE TABLE SoundSensor (
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    LocationId INTEGER,
	CreateAt DATETIME,
    UpdateAt DATETIME,
    FOREIGN KEY (LocationId) REFERENCES DeviceLocation(Id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS SoundSensorData;
CREATE TABLE SoundSensorData (
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    DeviceId INTEGER,
    Value DOUBLE,
    Time TIMESTAMP,
	CreateAt DATETIME,
    UpdateAt DATETIME,
    FOREIGN KEY (DeviceId) REFERENCES SoundSensor(Id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS GasSensor;
CREATE TABLE GasSensor (
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    LocationId INTEGER,
	CreateAt DATETIME,
    UpdateAt DATETIME,
    FOREIGN KEY (LocationId) REFERENCES DeviceLocation(Id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS GasSensorData;
CREATE TABLE GasSensorData (
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    DeviceId INTEGER,
    Value DOUBLE,
    Time TIMESTAMP,
	CreateAt DATETIME,
    UpdateAt DATETIME,
    FOREIGN KEY (DeviceId) REFERENCES GasSensor(Id)
		ON DELETE CASCADE ON UPDATE CASCADE
);


DROP TABLE IF EXISTS ChipiButtonSensor;
CREATE TABLE ChipiButtonSensor (
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    LocationId INTEGER,
	CreateAt DATETIME,
    UpdateAt DATETIME,
    FOREIGN KEY (LocationId) REFERENCES DeviceLocation(Id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS ChipiButtonSensorData;
CREATE TABLE ChipiButtonSensorData (
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    DeviceId INTEGER,
    Value BOOLEAN,
    Time TIMESTAMP,
	CreateAt DATETIME,
    UpdateAt DATETIME,
    FOREIGN KEY (DeviceId) REFERENCES ChipiButtonSensor(Id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Notification;
CREATE TABLE Notification(
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Content VARCHAR(1000),
    Time TIMESTAMP,
    Pos INTEGER,
	CreateAt DATETIME,
    UpdateAt DATETIME,
	FOREIGN KEY (pos) REFERENCES CrossRoad(Id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS TrafficSignal;
CREATE TABLE TrafficSignal(
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    LocationId INTEGER,
	CreateAt DATETIME,
    UpdateAt DATETIME,
	FOREIGN KEY (LocationId) REFERENCES DeviceLocation(Id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS TrafficSignalData;
CREATE TABLE TrafficSignalData(
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
	DeviceId INTEGER,
	Value Char(2), -- 00, 01, 11, 10,
	Time TIMESTAMP,
	CreateAt DATETIME,
    UpdateAt DATETIME,
	FOREIGN KEY (DeviceId) REFERENCES TrafficSignal(Id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS TrafficDensity;
CREATE TABLE TrafficDensity(
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
	LocationId INTEGER,
	Value DOUBLE,
	Time TIMESTAMP,
	CreateAt DATETIME,
    UpdateAt DATETIME,
	FOREIGN KEY (LocationId) REFERENCES DeviceLocation(Id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

-- SELECT CONCAT('ALTER TABLE `', TABLE_NAME, 
--               '` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;') 
-- FROM   INFORMATION_SCHEMA.TABLES 
-- WHERE  TABLE_SCHEMA = DATABASE() 
--        AND TABLE_TYPE LIKE 'BASE TABLE' ;
--        
-- SELECT CONCAT('ALTER TABLE `', TABLE_NAME, '` MODIFY COLUMN `', COLUMN_NAME,'` ', 
--               DATA_TYPE, IF(CHARACTER_MAXIMUM_LENGTH IS NULL 
--        OR DATA_TYPE LIKE 'longtext', '', CONCAT('(', CHARACTER_MAXIMUM_LENGTH, 
--                                          ')') 
--        ), ' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;')
-- FROM   INFORMATION_SCHEMA.COLUMNS 
-- WHERE  TABLE_SCHEMA = DATABASE()
--        AND (SELECT INFORMATION_SCHEMA.TABLES.TABLE_TYPE 
--             FROM   INFORMATION_SCHEMA.TABLES 
--             WHERE  INFORMATION_SCHEMA.TABLES.TABLE_SCHEMA = 
--                    INFORMATION_SCHEMA.COLUMNS.TABLE_SCHEMA 
--                    AND INFORMATION_SCHEMA.TABLES.TABLE_NAME = 
--                        INFORMATION_SCHEMA.COLUMNS.TABLE_NAME 
--             LIMIT  1) LIKE 'BASE TABLE' 
--        AND DATA_TYPE IN ( 'char', 'varchar' ) /* include other types if necessary */


ALTER TABLE `ChipiButtonSensor` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `ChipiButtonSensorData` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `CrossRoad` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `DeviceLocation` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `GasSensor` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `GasSensorData` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Notification` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Road` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `RoadCrossRoad` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `SoundSensor` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `SoundSensorData` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `TemperatureSensor` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `TemperatureSensorData` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `TrafficDensity` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `TrafficSignal` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `TrafficSignalData` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `User` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `CrossRoad` MODIFY COLUMN `Name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Notification` MODIFY COLUMN `Content` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Road` MODIFY COLUMN `Name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `TrafficSignalData` MODIFY COLUMN `Value` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `User` MODIFY COLUMN `Username` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `User` MODIFY COLUMN `Password` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `User` MODIFY COLUMN `UrlAvatar` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `User` MODIFY COLUMN `Name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `User` MODIFY COLUMN `Ranks` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `User` MODIFY COLUMN `WorkPlace` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `User` MODIFY COLUMN `IdNo` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `User` MODIFY COLUMN `Religion` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
